version: '3'

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
    command: "master -mdir /data -ip=master"
    volumes:
      - "./data/meta/:/data/"
    healthcheck:
      test: "curl http://localhost:9333/ -f || exit 1"
      interval: 10s
      timeout: 5s
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 9301:9301
    command: 'volume -max=30 -mserver="master:9333" -port=9301'
    volumes:
      - "./data/volume/:/data/"
    healthcheck:
      test: "curl http://localhost:9301/status -f || exit 1"
      interval: 10s
      timeout: 5s
    depends_on:
      - master
  mongodb:
    image: mongo:4
    ports:
      # Don't expose it maybe safer
      - 27018:27017
    # Set according your machine memory size
    command: --wiredTigerCacheSizeGB 0.7
    environment:
      # If the mongodb won't expose, maybe you can comment these settings
      MONGO_INITDB_ROOT_USERNAME: admin
      # todo: Change the password here in production
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - "./data/mongodb/:/data/db"
#  redis:
#    image: redis:5.0
#    ports:
#      - 6379:6379
#    volumes:
#      - "./data/redis/:/data/"
#  nemivir:
#    image: nemivir
#    ports:
#      - 8000:8000
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    environment:
#      REDIS_SERVER: redis://redis:6379/
#      FILER_SERVER: http://filer:9401/
#      prometheus_multiproc_dir: /prometheus_multiproc_dir
#      WEB_CONCURRENCY: 1
#      IMG_CACHE_TIMEOUT: 600
#    volumes:
#      - "./data/prometheus/:/prometheus_multiproc_dir"
#    depends_on:
#      - mongodb
#      - redis
#  nemivir_unit_test:
#    image: nemivir
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    command: "python3 -u unit_test.py"
#    volumes:
#      - "./test_images/:/data"
#    depends_on:
#      - nemivir