version: '3'

# weed/redis/...'s exposed port is only for debug

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333 # todo remove this port expose
    command: "master -mdir /data -ip=master"
    volumes:
      - "./data/meta/:/data/"
    healthcheck:
      test: "curl http://localhost:9333/ -f || exit 1"
      interval: 10s
      timeout: 5s
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 9301:9301 # todo remove this port expose
    command: 'volume -max=30 -mserver="master:9333" -port=9301'
    volumes:
      - "./data/volume/:/data/"
    healthcheck:
      test: "curl http://localhost:9301/status -f || exit 1"
      interval: 10s
      timeout: 5s
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 9401:9401 # todo remove this port expose
    command: 'filer -master="master:9333" -port=9401 -dirListLimit 1000000'
    volumes:
      - "./data/filer/:/data/filerldb2/"
    healthcheck:
      test: "curl 'http://localhost:9401/?limit=1' -f -H 'Accept: application/json'|| exit 1"
      interval: 10s
      timeout: 5s
    depends_on:
      - master
      - volume
  redis:
    image: redis:5.0
    ports:
      - 6379:6379 # todo remove this port expose
    volumes:
      - "./data/redis/:/data/"
  nemivir:
    image: nemivir
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      REDIS_SERVER: redis://redis:6379/
      FILER_SERVER: http://filer:9401/
      prometheus_multiproc_dir: /prometheus_multiproc_dir
      WEB_CONCURRENCY: 1
      IMG_CACHE_SIZE: 128
      IMG_CACHE_TIMEOUT: 600
    volumes:
      - "./data/prometheus/:/prometheus_multiproc_dir"
    depends_on:
      - filer
      - redis
  nemivir_unit_test:
    image: nemivir
    build:
      context: ./
      dockerfile: Dockerfile
    command: "python3 -u unit_test.py"
    volumes:
    - "./test_images/:/data"
    depends_on:
      - nemivir