version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up --build --force-recreate --exit-code-from nemivir_unit_test

